### ISSUE TITLE
On App's First Open - Send Android ID

### ISSUE THREAD

**Issue by jblairkiel** [sdeastcott/Troubadour#20]
This will /user POST ID on each app open.  Marcus says he can return a non-intrusive response code.

**Comment by jblairkiel** [comment]
On 'SharedServices'

**Comment by marcushill** [comment]
Do we still need a POST at /user for this? If so, I can easily throw up that API.

**Comment by jblairkiel** [comment]
I'm not sure how this is handled on the Backend.  If a user creates preferences for the first time, is this needed?

**Comment by marcushill** [comment]
So at the moment, there's never a point when the app creates a user. It's
done as a side effect of putting preferences for the first time or sending
a location. This issue was opened to have an explicit method of user
creation

**Comment by jblairkiel** [comment]
Closed it is.
