### ISSUE TITLE
Fix Redirect URIs on Spotify Developer Console

### ISSUE THREAD

**Issue by marcushill** [sdeastcott/Troubadour#37]
You two should probably get together on this at some point. @jwlichtle should know what this is.

**Comment by jwlichtle** [comment]
@jblairkiel this is a simple fix. You just need to go back to the developer page and make sure you have the redirect uri's saved. I think you may have added them and not saved them.

**Comment by jblairkiel** [comment]
@jwlichtle You are correct sir.  I saved the URI's this time.

**Comment by jwlichtle** [comment]
I'm going to go ahead and close this then.
