### ISSUE TITLE
Encapsulate API Calls in APIHandler Class

### ISSUE THREAD

**Issue by jblairkiel** [sdeastcott/Troubadour#5]
Our API calls will get very messy over time with the amount of private ASync classes that will have to be made.  Each one has to update 'onPostExecute' however I have yet to figure out a good way to wrap them all in the APIHandler class.

**Comment by marcushill** [comment]
If you check in the technical references file in Drive, there's a link to
how to set up Java 8 lambda support. It'll help with the anonymous classes
a bit.

**Comment by marcushill** [comment]
@jblairkiel Have you seen this? https://developer.android.com/training/volley/simple.html . It might help.

**Comment by jblairkiel** [comment]
@marcushill I'm having trouble using multiple callbacks (get and post have different outcomes).  I will need help wrapping my mind around how to solve this.  Check out multiple interfaces in java.

**Comment by marcushill** [comment]
@jblairkiel I'll look into it around lunch time. Can you branch and push code? I'm not super familiar with the app code and it'll help if I can see what specific section is giving you a problem.

**Comment by marcushill** [comment]
Take a look at this: http://stackoverflow.com/questions/28172496/android-volley-how-to-isolate-requests-in-another-class . I'm still looking, but I thought this might be helpful for what you're doing in general.

**Comment by jblairkiel** [comment]
@marcushill Whatever works best, I'm fine with JSONObjects or regular classes.

**Comment by marcushill** [comment]
I opened #13 to have something to reference. 

What I did was turn on Java 8 support and create two new classes named TroubadourArrayRequest and TroubadourObjectRequest. Use them instead of JsonArrayRequest and JsonObjectRequest respectively. I did this simply to clean up the code. Instead of this:

```java
new JsonObjectRequest(...){
@Override
public Map<String, String> getHeaders(){
// Code here
}
}
```

You do: 
```java
TroubadourObjectRequest t = new TroubadourObjectRequest(...);
t.addHeader("key1", "value1")
 .addHeader("key2", "value2");
```
