### ISSUE TITLE
UI Cooldown to assist Spotify API rate limits

### ISSUE THREAD

**Issue by jblairkiel** [sdeastcott/Troubadour#8]
We need to investigate putting a cooldown on some of the UI widgets.  What if a ton of users just spam a refresh button that keeps calling Spotify API until they serve us a 429 "Too Many Requests"?

**Comment by marcushill** [comment]
Throttle and/or debounce are the words you're looking for. I agree with your point though. This should be pretty easy to implement assuming Java doesn't get in the way.
